### ISSUE TITLE
No module named 'korrigjo'

### ISSUE THREAD

**Issue by Irdiism** [erionc/alb-spell-fix#2]
Kur i bej run me python dritare.py me jep errorin e meposhtem:

Traceback (most recent call last):
  File "dritare.py", line 7, in <module>
    from korrigjo import *
ModuleNotFoundError: No module named 'korrigjo'

**Comment by erionc** [comment]
Përshëndetje!

Kisha bërë disa riemërtime të skedarëve të cilat kisha harruar t'i pasqyroja te importimet. Tani duhet të jetë në rregull. 

Faleminderit për raportimin.
